Update LGPL3-Windows&Linux.yaml

diff --git a/.github/workflows/LGPL3-Windows&Linux.yaml b/.github/workflows/LGPL3-Windows&Linux.yaml
--- a/.github/workflows/LGPL3-Windows&Linux.yaml
+++ b/.github/workflows/LGPL3-Windows&Linux.yaml
@@ -101,28 +101,37 @@ jobs:
         tar -xzf amf.tar.gz
         mkdir -p $HOME/target_build/include/AMF && cp -r AMF-master/amf/public/include/* $HOME/target_build/include/AMF/
 
-    # 4. 构建 FFmpeg
     - name: Build FFmpeg
       run: |
-        # 这里的路径必须包含 x86_64-linux-gnu，因为很多 Linux 发行版会把库塞进去
         export PKG_CONFIG_PATH=$HOME/target_build/lib/pkgconfig:$HOME/target_build/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
         
         COMMON_ARGS="--prefix=$HOME/publish --enable-version3 --disable-gpl --disable-nonfree --enable-static --disable-shared --disable-all --enable-ffmpeg --enable-ffprobe --enable-avcodec --enable-avformat --enable-avfilter --enable-swresample --enable-swscale --enable-libvpl --enable-libkvazaar --enable-encoder=hevc_qsv,h264_qsv,libkvazaar --enable-decoder=h264,hevc,vp9,av1 --enable-demuxer=mov,mp4,m4a,yuv4mpegpipe,h264,hevc --enable-muxer=mp4,mov --enable-protocol=file,http,https,tcp,udp"
         
+        # 尝试执行 configure，如果失败则打印日志
         if [ "${{ matrix.target }}" = "linux" ]; then
           ./configure $COMMON_ARGS \
             --enable-vaapi --enable-libdav1d --enable-libvpx --enable-libaom --enable-libopus --enable-encoder=h264_vaapi,hevc_vaapi,h264_nvenc,hevc_nvenc,amf \
             --extra-cflags="-I$HOME/target_build/include" \
-            --extra-ldflags="-L$HOME/target_build/lib -L$HOME/target_build/lib/x86_64-linux-gnu -lstdc++ -lpthread -lm -ldl"
+            --extra-ldflags="-L$HOME/target_build/lib -L$HOME/target_build/lib/x86_64-linux-gnu -lstdc++ -lpthread -lm -ldl" || \
+          { 
+            echo "--- CONFIGURE FAILED: SHOWING LAST 100 LINES OF config.log ---"; 
+            tail -n 100 ffbuild/config.log; 
+            exit 1; 
+          }
         else
-          # Windows 交叉编译
           ./configure $COMMON_ARGS \
             --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- \
             --pkg-config-flags="--static" \
             --enable-encoder=h264_nvenc,hevc_nvenc,amf \
             --extra-cflags="-I$HOME/target_build/include" \
-            --extra-ldflags="-L$HOME/target_build/lib -static -lstdc++"
+            --extra-ldflags="-L$HOME/target_build/lib -static -lstdc++" || \
+          { 
+            echo "--- CONFIGURE FAILED: SHOWING LAST 100 LINES OF config.log ---"; 
+            tail -n 100 ffbuild/config.log; 
+            exit 1; 
+          }
         fi
+
         make -j$(nproc)
         make install
 
